[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "nerfacc"
version = "0.0.3"
authors = [{name = "Ruilong", email = "ruilongli94@gmail.com"}]
license = { text="MIT" }
requires-python = ">=3.8"
dependencies = [
    "ninja>=1.10.2.3",
    "pybind11>=2.10.0",
    "torch>=1.12.1"
]

[project.optional-dependencies]
# for example scripts
examples = [
    "tinycudann @ git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch",
    "opencv-python",
    "imageio",
    "numpy",
    "tqdm",
]

# for documentation
docs = []